# Generated by Django 2.2.6 on 2019-12-02 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLIStudentMasterSheetUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.FileField(help_text='The upload binary file.', upload_to='uploads/%Y/%m/')),
                ('title', models.CharField(blank=True, help_text='The tile content of this upload.', max_length=63, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='The text content of this upload.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'URL Request File Upload',
                'verbose_name_plural': 'URL Request File Uploads',
                'db_table': 'burrow_url_request_file_uploads',
                'permissions': (),
                'default_permissions': (),
            },
        ),
    ]
