# Generated by Django 2.2.6 on 2019-12-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0002_auto_20191202_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLIStudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('student_id', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('pathway', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('email_address', models.EmailField(max_length=254)),
                ('immigration_status', models.CharField(max_length=50)),
                ('immigration_status_valid_date', models.DateField()),
                ('insurance_valid_date', models.DateField()),
                ('payment_through', models.CharField(max_length=255)),
                ('payment_valid_date', models.DateField()),
                ('if_have_student_file', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='llistudentmastersheetupload',
            name='description',
            field=models.TextField(blank=True, help_text='The description content of this upload.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='llistudentmastersheetupload',
            name='title',
            field=models.CharField(blank=True, help_text='The tile of this upload.', max_length=63, null=True, verbose_name='Title'),
        ),
    ]
