# Generated by Django 2.2.6 on 2019-12-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0003_auto_20191203_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llistudentdata',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='if_have_student_file',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='immigration_status',
            field=models.CharField(blank=True, help_text='Study permit, work permit, visitor, PR, or Canadian citizen', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='immigration_status_valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='insurance_valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='level',
            field=models.CharField(blank=True, help_text='student current level.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='pathway',
            field=models.CharField(blank=True, help_text='Is this a pathway student, please answer yes or no.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='payment_through',
            field=models.CharField(blank=True, help_text='Self or agent', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='payment_valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='photo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='llistudentdata',
            name='student_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
