# Generated by Django 2.2.6 on 2019-12-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0004_auto_20191203_1519'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llistudentdata',
            options={'default_permissions': (), 'permissions': (), 'verbose_name': 'LLI Student Master Sheet datum', 'verbose_name_plural': 'LLI Student Master Sheet data'},
        ),
        migrations.AlterModelTable(
            name='llistudentdata',
            table='lli_student_data',
        ),
    ]
