# Generated by Django 2.2.6 on 2019-12-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0006_llistudentdata_was_immigration_status_valid_date_dealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='llistudentdata',
            name='was_insurance_valid_date_dealt',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='llistudentdata',
            name='was_payment_valid_date_dealt',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
